name: just_chat
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.3.4
  cupertino_icons: 1.0.8
  dio: 5.7.0
  easy_localization: ^3.0.7
  firebase_core: ^3.5.0 # to init firebase in the project 
  firebase_auth: ^5.3.1 # to use firebase auth
  cloud_firestore: ^5.4.3 # NoSql database structured with docs and collections
  firebase_storage: ^12.3.2 # to store medial like images and videos in firebase.
  firebase_messaging: ^15.1.3 # to send push notifications to users when new messages are received.
  firebase_analytics: ^11.3.3 # to track user behavior for insights and app improvements.
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_ripple: ^0.0.3
  flutter_screenutil: 5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  intl: 0.19.0
  pretty_dio_logger: 1.4.0
  shared_preferences: ^2.3.2
  # this package for shimmer or flashing effect on buttons 
  shimmer_animation: ^2.2.1
  # this package for drawing shimmer without need to build it from scratch
  skeletonizer: ^1.4.2
  awesome_dialog: ^3.2.1
  lottie: ^3.1.2
  intl_phone_number_input: ^0.7.4
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/
    - assets/lotties/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
    - family: BrittanySignature
      fonts:
        - asset: assets/fonts/BrittanySignature.ttf
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic.ttf
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
