// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR2AWKUrDOAfTULygB7FrWIgatr1VsXbo',
    appId: '1:215010547123:web:d401e9b016f9963f0ee7c6',
    messagingSenderId: '215010547123',
    projectId: 'just-chat-afd29',
    authDomain: 'just-chat-afd29.firebaseapp.com',
    storageBucket: 'just-chat-afd29.appspot.com',
    measurementId: 'G-3HVJH9YYJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQS1lzoLP4e8OiaLjkqDPhIwGJqndPMm0',
    appId: '1:215010547123:android:4982ff19195a606e0ee7c6',
    messagingSenderId: '215010547123',
    projectId: 'just-chat-afd29',
    storageBucket: 'just-chat-afd29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpWCtwUv0I-ig8koyF6hS8pFANZg9aqn8',
    appId: '1:215010547123:ios:43346141cdbd8f090ee7c6',
    messagingSenderId: '215010547123',
    projectId: 'just-chat-afd29',
    storageBucket: 'just-chat-afd29.appspot.com',
    iosBundleId: 'com.example.justChat',
  );
}
